package entity;
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsDistrito generated by hbm2java
 */
public class UcsawsDistrito implements java.io.Serializable {

	private Integer idDistrito;
	private UcsawsDepartamento ucsawsDepartamento;
	private String descDistrito;
	private String nroDistrito;
	private String usuarioIns;
	private String usuarioUpd;
	private Date fchIns;
	private Date fchUpd;
	private UcsawsEvento idEvento;


	public UcsawsDistrito() {
	}

	public UcsawsDistrito(Integer idDistrito,
			UcsawsDepartamento ucsawsDepartamento, UcsawsEvento idEvento) {
		this.idDistrito = idDistrito;
		this.ucsawsDepartamento = ucsawsDepartamento;
		this.idEvento = idEvento;
	}

	public UcsawsDistrito(Integer idDistrito,
			UcsawsDepartamento ucsawsDepartamento, String descDistrito,
			String nroDistrito, String usuarioIns, String usuarioUpd,
			Date fchIns, Date fchUpd, UcsawsEvento idEvento) {
		this.idDistrito = idDistrito;
		this.ucsawsDepartamento = ucsawsDepartamento;
		this.descDistrito = descDistrito;
		this.nroDistrito = nroDistrito;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public Integer getIdDistrito() {
		return this.idDistrito;
	}

	public void setIdDistrito(Integer idDistrito) {
		this.idDistrito = idDistrito;
	}

	public UcsawsDepartamento getUcsawsDepartamento() {
		return this.ucsawsDepartamento;
	}

	public void setUcsawsDepartamento(UcsawsDepartamento ucsawsDepartamento) {
		this.ucsawsDepartamento = ucsawsDepartamento;
	}

	public String getDescDistrito() {
		return this.descDistrito;
	}

	public void setDescDistrito(String descDistrito) {
		this.descDistrito = descDistrito;
	}

	public String getNroDistrito() {
		return this.nroDistrito;
	}

	public void setNroDistrito(String nroDistrito) {
		this.nroDistrito = nroDistrito;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

	

}
