package entity;// default package
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsLocal generated by hbm2java
 */
public class UcsawsLocal implements java.io.Serializable {

	private Integer idLocal;
	private UcsawsZona ucsawsZona;
	private String descLocal;
	private String nroLocal;
	private String usuarioIns;
	private String usuarioUpd;
	private Date fchIns;
	private Date fchUpd;
	private UcsawsEvento idEvento;
	

	public UcsawsLocal() {
	}

	public UcsawsLocal(Integer idLocal, UcsawsEvento idEvento) {
		this.idLocal = idLocal;
		this.idEvento = idEvento;
	}

	public UcsawsLocal(Integer idLocal, UcsawsZona ucsawsZona, String descLocal,
			String nroLocal, String usuarioIns, String usuarioUpd, Date fchIns,
			Date fchUpd, UcsawsEvento idEvento) {
		this.idLocal = idLocal;
		this.ucsawsZona = ucsawsZona;
		this.descLocal = descLocal;
		this.nroLocal = nroLocal;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public Integer getIdLocal() {
		return this.idLocal;
	}

	public void setIdLocal(Integer idLocal) {
		this.idLocal = idLocal;
	}

	public UcsawsZona getUcsawsZona() {
		return this.ucsawsZona;
	}

	public void setUcsawsZona(UcsawsZona ucsawsZona) {
		this.ucsawsZona = ucsawsZona;
	}

	public String getDescLocal() {
		return this.descLocal;
	}

	public void setDescLocal(String descLocal) {
		this.descLocal = descLocal;
	}

	public String getNroLocal() {
		return this.nroLocal;
	}

	public void setNroLocal(String nroLocal) {
		this.nroLocal = nroLocal;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

	

}
