package entity;
// Generated 27/04/2017 10:00:56 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UcsawsVotosBlanco generated by hbm2java
 */
public class UcsawsVotosBlanco implements java.io.Serializable {

	private Integer idVotoBlanco;
	private UcsawsTipoLista idTipoLista;
	private UcsawsMesa idMesa;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private UcsawsEvento idEvento;

	public UcsawsVotosBlanco() {
	}

	public UcsawsVotosBlanco(Integer idVotoBlanco, UcsawsTipoLista idTipoLista, UcsawsMesa idMesa,
			Date fchIns, String usuarioIns, UcsawsEvento idEvento) {
		this.idVotoBlanco = idVotoBlanco;
		this.idTipoLista = idTipoLista;
		this.idMesa = idMesa;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.idEvento = idEvento;
	}

	public UcsawsVotosBlanco(Integer idVotoBlanco, UcsawsTipoLista idTipoLista, UcsawsMesa idMesa,
			Date fchIns, Date fchUpd, String usuarioIns, String usuarioUpd,
			UcsawsEvento idEvento) {
		this.idVotoBlanco = idVotoBlanco;
		this.idTipoLista = idTipoLista;
		this.idMesa = idMesa;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.idEvento = idEvento;
	}

	public Integer getIdVotoBlanco() {
		return this.idVotoBlanco;
	}

	public void setIdVotoBlanco(Integer idVotoBlanco) {
		this.idVotoBlanco = idVotoBlanco;
	}

	public UcsawsTipoLista getIdTipoLista() {
		return this.idTipoLista;
	}

	public void setIdTipoLista(UcsawsTipoLista idTipoLista) {
		this.idTipoLista = idTipoLista;
	}

	public UcsawsMesa getIdMesa() {
		return this.idMesa;
	}

	public void setIdMesa(UcsawsMesa idMesa) {
		this.idMesa = idMesa;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

}
