package entity;
// Generated 22/04/2017 10:08:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UcsawsEvento generated by hbm2java
 */
public class UcsawsEvento implements java.io.Serializable {

	private Integer idEvento;
	private UcsawsTipoEvento ucsawsTipoEvento;
	private String descripcion;
	private Date fchDesde;
	private Date fchHasta;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private String nroEvento;

	public UcsawsEvento() {
	}

	public UcsawsEvento(Integer idEvento, UcsawsTipoEvento ucsawsTipoEvento,
			Date fchDesde, Date fchHasta, Date fchIns, String usuarioIns,
			String nroEvento) {
		this.idEvento = idEvento;
		this.ucsawsTipoEvento = ucsawsTipoEvento;
		this.fchDesde = fchDesde;
		this.fchHasta = fchHasta;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.nroEvento = nroEvento;
	}

	public UcsawsEvento(Integer idEvento, UcsawsTipoEvento ucsawsTipoEvento,
			String descripcion, Date fchDesde, Date fchHasta, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd, String nroEvento) {
		this.idEvento = idEvento;
		this.ucsawsTipoEvento = ucsawsTipoEvento;
		this.descripcion = descripcion;
		this.fchDesde = fchDesde;
		this.fchHasta = fchHasta;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.nroEvento = nroEvento;
	}

	public Integer getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	public UcsawsTipoEvento getUcsawsTipoEvento() {
		return this.ucsawsTipoEvento;
	}

	public void setUcsawsTipoEvento(UcsawsTipoEvento ucsawsTipoEvento) {
		this.ucsawsTipoEvento = ucsawsTipoEvento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFchDesde() {
		return this.fchDesde;
	}

	public void setFchDesde(Date fchDesde) {
		this.fchDesde = fchDesde;
	}

	public Date getFchHasta() {
		return this.fchHasta;
	}

	public void setFchHasta(Date fchHasta) {
		this.fchHasta = fchHasta;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getNroEvento() {
		return this.nroEvento;
	}

	public void setNroEvento(String nroEvento) {
		this.nroEvento = nroEvento;
	}

}
