package entity;

// default package
// Generated 30/05/2017 06:35:51 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UcsawsCandidatos generated by hbm2java
 */
public class UcsawsCandidatos implements java.io.Serializable {

    private Integer idCandidatos;
    private UcsawsPersona idPersona;
    private UcsawsListas idLista;
    private Date fchIns;
    private Date fchUpd;
    private String usuarioIns;
    private String usuarioUpd;
    private String codigo;
    private UcsawsEvento idEvento;
    private String descripcion;

    public UcsawsCandidatos() {
    }

    public UcsawsCandidatos(Integer idCandidatos, UcsawsPersona idPersona,
	    UcsawsListas idLista, Date fchIns, String usuarioIns,
	    UcsawsEvento idEvento) {
	this.idCandidatos = idCandidatos;
	this.idPersona = idPersona;
	this.idLista = idLista;
	this.fchIns = fchIns;
	this.usuarioIns = usuarioIns;
	this.idEvento = idEvento;
    }

    public UcsawsCandidatos(Integer idCandidatos, UcsawsPersona idPersona,
	    UcsawsListas idLista, Date fchIns, Date fchUpd, String usuarioIns,
	    String usuarioUpd, String codigo, UcsawsEvento idEvento,
	    String descripcion) {
	this.idCandidatos = idCandidatos;
	this.idPersona = idPersona;
	this.idLista = idLista;
	this.fchIns = fchIns;
	this.fchUpd = fchUpd;
	this.usuarioIns = usuarioIns;
	this.usuarioUpd = usuarioUpd;
	this.codigo = codigo;
	this.idEvento = idEvento;
	this.descripcion = descripcion;
    }

    public Integer getIdCandidatos() {
	return this.idCandidatos;
    }

    public void setIdCandidatos(Integer idCandidatos) {
	this.idCandidatos = idCandidatos;
    }

    public Date getFchIns() {
	return this.fchIns;
    }

    public void setFchIns(Date fchIns) {
	this.fchIns = fchIns;
    }

    public Date getFchUpd() {
	return this.fchUpd;
    }

    public void setFchUpd(Date fchUpd) {
	this.fchUpd = fchUpd;
    }

    public String getUsuarioIns() {
	return this.usuarioIns;
    }

    public void setUsuarioIns(String usuarioIns) {
	this.usuarioIns = usuarioIns;
    }

    public String getUsuarioUpd() {
	return this.usuarioUpd;
    }

    public void setUsuarioUpd(String usuarioUpd) {
	this.usuarioUpd = usuarioUpd;
    }

    public String getCodigo() {
	return this.codigo;
    }

    public void setCodigo(String codigo) {
	this.codigo = codigo;
    }

    public String getDescripcion() {
	return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
	this.descripcion = descripcion;
    }

    public UcsawsPersona getIdPersona() {
        return idPersona;
    }

    public void setIdPersona(UcsawsPersona idPersona) {
        this.idPersona = idPersona;
    }

    public UcsawsListas getIdLista() {
        return idLista;
    }

    public void setIdLista(UcsawsListas idLista) {
        this.idLista = idLista;
    }

    public UcsawsEvento getIdEvento() {
        return idEvento;
    }

    public void setIdEvento(UcsawsEvento idEvento) {
        this.idEvento = idEvento;
    }
    
    

}
