package entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsNacionalidad generated by hbm2java
 */
public class UcsawsNacionalidad implements java.io.Serializable {

	private Integer idNacionalidad;
	private UcsawsPais ucsawsPais;
	private String codNacionalidad;
	private String descNacionalidad;
	private String usuarioIns;
	private String usuarioUpd;
	private Date fchIns;
	private Date fchUpd;
	private UcsawsEvento idEvento;
	

	public UcsawsNacionalidad() {
	}

	public UcsawsNacionalidad(Integer idNacionalidad, UcsawsPais ucsawsPais) {
		this.idNacionalidad = idNacionalidad;
		this.ucsawsPais = ucsawsPais;
	}

	public UcsawsNacionalidad(Integer idNacionalidad, UcsawsPais ucsawsPais,
			String codNacionalidad, String descNacionalidad, String usuarioIns,
			String usuarioUpd, Date fchIns, Date fchUpd, UcsawsEvento idEvento,
			Set ucsawsPersonas) {
		this.idNacionalidad = idNacionalidad;
		this.ucsawsPais = ucsawsPais;
		this.codNacionalidad = codNacionalidad;
		this.descNacionalidad = descNacionalidad;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public Integer getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(Integer idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	public UcsawsPais getUcsawsPais() {
		return this.ucsawsPais;
	}

	public void setUcsawsPais(UcsawsPais ucsawsPais) {
		this.ucsawsPais = ucsawsPais;
	}

	public String getCodNacionalidad() {
		return this.codNacionalidad;
	}

	public void setCodNacionalidad(String codNacionalidad) {
		this.codNacionalidad = codNacionalidad;
	}

	public String getDescNacionalidad() {
		return this.descNacionalidad;
	}

	public void setDescNacionalidad(String descNacionalidad) {
		this.descNacionalidad = descNacionalidad;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}



}
