package entity;
// Generated 27/04/2017 04:02:20 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UcsawsVotos generated by hbm2java
 */
public class UcsawsVotos implements java.io.Serializable {

	private Integer idVoto;
	private UcsawsListas idLista;
	private UcsawsMesa idMesa;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;

	public UcsawsVotos() {
	}

	public UcsawsVotos(Integer idVoto, UcsawsListas idLista, UcsawsMesa idMesa, Date fchIns,
			String usuarioIns) {
		this.idVoto = idVoto;
		this.idLista = idLista;
		this.idMesa = idMesa;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
	}

	public UcsawsVotos(Integer idVoto, UcsawsListas idLista, UcsawsMesa idMesa, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd) {
		this.idVoto = idVoto;
		this.idLista = idLista;
		this.idMesa = idMesa;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
	}

	public Integer getIdVoto() {
		return this.idVoto;
	}

	public void setIdVoto(Integer idVoto) {
		this.idVoto = idVoto;
	}

	public UcsawsListas getIdLista() {
		return this.idLista;
	}

	public void setIdLista(UcsawsListas idLista) {
		this.idLista = idLista;
	}

	public UcsawsMesa getIdMesa() {
		return this.idMesa;
	}

	public void setIdMesa(UcsawsMesa idMesa) {
		this.idMesa = idMesa;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

}
