package entity;
// Generated 26/04/2017 09:41:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UcsawsListas generated by hbm2java
 */
public class UcsawsListas implements java.io.Serializable {

	private Integer idLista;
	private UcsawsTipoLista ucsawsTipoLista;
	private String nombreLista;
	private Integer anho;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private Integer nroLista;
	private UcsawsEvento idEvento;

	public UcsawsListas() {
	}

	public UcsawsListas(Integer idLista, String nombreLista, Integer anho, Date fchIns,
			String usuarioIns, UcsawsEvento idEvento) {
		this.idLista = idLista;
		this.nombreLista = nombreLista;
		this.anho = anho;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.idEvento = idEvento;
	}

	public UcsawsListas(Integer idLista, UcsawsTipoLista ucsawsTipoLista,
			String nombreLista, Integer anho, Date fchIns, Date fchUpd,
			String usuarioIns, String usuarioUpd, Integer nroLista, UcsawsEvento idEvento) {
		this.idLista = idLista;
		this.ucsawsTipoLista = ucsawsTipoLista;
		this.nombreLista = nombreLista;
		this.anho = anho;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.nroLista = nroLista;
		this.idEvento = idEvento;
	}

	public Integer getIdLista() {
		return this.idLista;
	}

	public void setIdLista(Integer idLista) {
		this.idLista = idLista;
	}

	public UcsawsTipoLista getUcsawsTipoLista() {
		return this.ucsawsTipoLista;
	}

	public void setUcsawsTipoLista(UcsawsTipoLista ucsawsTipoLista) {
		this.ucsawsTipoLista = ucsawsTipoLista;
	}

	public String getNombreLista() {
		return this.nombreLista;
	}

	public void setNombreLista(String nombreLista) {
		this.nombreLista = nombreLista;
	}

	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Integer getNroLista() {
		return this.nroLista;
	}

	public void setNroLista(Integer nroLista) {
		this.nroLista = nroLista;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

}
