package entity;
// Generated 25/04/2017 03:26:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UcsawsUsers generated by hbm2java
 */
public class UcsawsUsers implements java.io.Serializable {

	private Integer idUser;
	private UcsawsPersona ucsawsPersona;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private String pass;
	private Boolean esAdmin;
	private String usuario;
	private UcsawsEvento idEvento;
	private UcsawsRoles idRol;

	public UcsawsUsers() {
	}

	public UcsawsUsers(Integer idUser, UcsawsPersona ucsawsPersona, Date fchIns,
			String usuarioIns) {
		this.idUser = idUser;
		this.ucsawsPersona = ucsawsPersona;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
	}

	public UcsawsUsers(Integer idUser, UcsawsPersona ucsawsPersona, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd, String pass,
			Boolean esAdmin, String usuario, UcsawsEvento idEvento, UcsawsRoles idRol) {
		this.idUser = idUser;
		this.ucsawsPersona = ucsawsPersona;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.pass = pass;
		this.esAdmin = esAdmin;
		this.usuario = usuario;
		this.idEvento = idEvento;
		this.idRol = idRol;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public UcsawsPersona getUcsawsPersona() {
		return this.ucsawsPersona;
	}

	public void setUcsawsPersona(UcsawsPersona ucsawsPersona) {
		this.ucsawsPersona = ucsawsPersona;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Boolean getEsAdmin() {
		return this.esAdmin;
	}

	public void setEsAdmin(Boolean esAdmin) {
		this.esAdmin = esAdmin;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}

	public UcsawsRoles getIdRol() {
		return this.idRol;
	}

	public void setIdRol(UcsawsRoles idRol) {
		this.idRol = idRol;
	}

}
