package entity;
// Generated 25/04/2017 03:26:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsGenero generated by hbm2java
 */
public class UcsawsGenero implements java.io.Serializable {

	private Integer idGenero;
	private String descripcion;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private String codigo;
	private Integer idEvento;
	 
	//private Set ucsawsPersonas = new HashSet(0);

	public UcsawsGenero() {
	}

	public UcsawsGenero(Integer idGenero, String descripcion, Date fchIns,
			String usuarioIns, Integer idEvento) {
		this.idGenero = idGenero;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.idEvento = idEvento;
	}

	public UcsawsGenero(Integer idGenero, String descripcion, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd, String codigo,
			Integer idEvento) {
		this.idGenero = idGenero;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.codigo = codigo;
		this.idEvento = idEvento;
		
	}

	public Integer getIdGenero() {
		return this.idGenero;
	}

	public void setIdGenero(Integer idGenero) {
		this.idGenero = idGenero;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Integer getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

 


}
