package entity;// default package
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsZona generated by hbm2java
 */
public class UcsawsZona implements java.io.Serializable {

	private int idZona;
	private UcsawsDistrito ucsawsDistrito;
	private String descZona;
	private String nroZona;
	private String usuarioIns;
	private String usuarioUpd;
	private Date fchIns;
	private Date fchUpd;
	private UcsawsEvento idEvento;
	

	public UcsawsZona() {
	}

	public UcsawsZona(int idZona, UcsawsDistrito ucsawsDistrito, UcsawsEvento idEvento) {
		this.idZona = idZona;
		this.ucsawsDistrito = ucsawsDistrito;
		this.idEvento = idEvento;
	}

	public UcsawsZona(int idZona, UcsawsDistrito ucsawsDistrito,
			String descZona, String nroZona, String usuarioIns,
			String usuarioUpd, Date fchIns, Date fchUpd, UcsawsEvento idEvento) {
		this.idZona = idZona;
		this.ucsawsDistrito = ucsawsDistrito;
		this.descZona = descZona;
		this.nroZona = nroZona;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.idEvento = idEvento;
		
	}

	public int getIdZona() {
		return this.idZona;
	}

	public void setIdZona(int idZona) {
		this.idZona = idZona;
	}

	public UcsawsDistrito getUcsawsDistrito() {
		return this.ucsawsDistrito;
	}

	public void setUcsawsDistrito(UcsawsDistrito ucsawsDistrito) {
		this.ucsawsDistrito = ucsawsDistrito;
	}

	public String getDescZona() {
		return this.descZona;
	}

	public void setDescZona(String descZona) {
		this.descZona = descZona;
	}

	public String getNroZona() {
		return this.nroZona;
	}

	public void setNroZona(String nroZona) {
		this.nroZona = nroZona;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}



}
