package entity;
// default package
// Generated 26/04/2017 09:41:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsTipoLista generated by hbm2java
 */
public class UcsawsTipoLista implements java.io.Serializable {

	private Integer idTipoLista;
	private String descripcion;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private String codigo;
	private UcsawsEvento idEvento;
	

	public UcsawsTipoLista() {
	}

	public UcsawsTipoLista(Integer idTipoLista, String descripcion, Date fchIns,
			String usuarioIns, String codigo) {
		this.idTipoLista = idTipoLista;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.codigo = codigo;
	}

	public UcsawsTipoLista(Integer idTipoLista, String descripcion, Date fchIns,
			Date fchUpd, String usuarioIns, String usuarioUpd, String codigo,
			UcsawsEvento idEvento) {
		this.idTipoLista = idTipoLista;
		this.descripcion = descripcion;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.codigo = codigo;
		this.idEvento = idEvento;		
	}

	public Integer getIdTipoLista() {
		return this.idTipoLista;
	}

	public void setIdTipoLista(Integer idTipoLista) {
		this.idTipoLista = idTipoLista;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}



}
