package entity;// default package
// Generated 25/04/2017 09:24:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsMesa generated by hbm2java
 */
public class UcsawsMesa implements java.io.Serializable {

	private Integer idMesa;
	private UcsawsLocal ucsawsLocal;
	private String descMesa;
	private String usuarioIns;
	private String usuarioUpd;
	private Date fchIns;
	private Date fchUpd;
	private Integer nroMesa;
	private UcsawsEvento idEvento;
	

	public UcsawsMesa() {
	}

	public UcsawsMesa(Integer idMesa) {
		this.idMesa = idMesa;
	}

	public UcsawsMesa(Integer idMesa, UcsawsLocal ucsawsLocal, String descMesa,
			String usuarioIns, String usuarioUpd, Date fchIns, Date fchUpd,
			Integer nroMesa, UcsawsEvento idEvento) {
		this.idMesa = idMesa;
		this.ucsawsLocal = ucsawsLocal;
		this.descMesa = descMesa;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.nroMesa = nroMesa;
		this.idEvento = idEvento;
		
	}

	public Integer getIdMesa() {
		return this.idMesa;
	}

	public void setIdMesa(Integer idMesa) {
		this.idMesa = idMesa;
	}

	public UcsawsLocal getUcsawsLocal() {
		return this.ucsawsLocal;
	}

	public void setUcsawsLocal(UcsawsLocal ucsawsLocal) {
		this.ucsawsLocal = ucsawsLocal;
	}

	public String getDescMesa() {
		return this.descMesa;
	}

	public void setDescMesa(String descMesa) {
		this.descMesa = descMesa;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public Integer getNroMesa() {
		return this.nroMesa;
	}

	public void setNroMesa(Integer nroMesa) {
		this.nroMesa = nroMesa;
	}

	public UcsawsEvento getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}


}
