package entity;
// Generated 25/04/2017 03:26:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcsawsPais generated by hbm2java
 */
public class UcsawsPais implements java.io.Serializable {

	private Integer idPais;
	private Date fchIns;
	private Date fchUpd;
	private String usuarioIns;
	private String usuarioUpd;
	private String nombre;
	private String codigo;
	private UcsawsEvento idEvento;


	public UcsawsPais() {
	}

	public UcsawsPais(Integer idPais, Date fchIns, String usuarioIns,
			String nombre, UcsawsEvento idEvento) {
		this.idPais = idPais;
		this.fchIns = fchIns;
		this.usuarioIns = usuarioIns;
		this.nombre = nombre;
		this.idEvento = idEvento;
	}

	public UcsawsPais(Integer idPais, Date fchIns, Date fchUpd, String usuarioIns,
			String usuarioUpd, String nombre, String codigo, UcsawsEvento idEvento) {
		this.idPais = idPais;
		this.fchIns = fchIns;
		this.fchUpd = fchUpd;
		this.usuarioIns = usuarioIns;
		this.usuarioUpd = usuarioUpd;
		this.nombre = nombre;
		this.codigo = codigo;
		this.idEvento = idEvento;
		
	}

	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	public Date getFchIns() {
		return this.fchIns;
	}

	public void setFchIns(Date fchIns) {
		this.fchIns = fchIns;
	}

	public Date getFchUpd() {
		return this.fchUpd;
	}

	public void setFchUpd(Date fchUpd) {
		this.fchUpd = fchUpd;
	}

	public String getUsuarioIns() {
		return this.usuarioIns;
	}

	public void setUsuarioIns(String usuarioIns) {
		this.usuarioIns = usuarioIns;
	}

	public String getUsuarioUpd() {
		return this.usuarioUpd;
	}

	public void setUsuarioUpd(String usuarioUpd) {
		this.usuarioUpd = usuarioUpd;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public UcsawsEvento getIdEvento() {
		return idEvento;
	}

	public void setIdEvento(UcsawsEvento idEvento) {
		this.idEvento = idEvento;
	}



}
