package entity;
// Generated 22/04/2017 08:25:44 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int userid;
	private String firstname;
	private String lastname;
	private Date dob;
	private String email;

	public Users() {
	}

	public Users(int userid, String firstname) {
		this.userid = userid;
		this.firstname = firstname;
	}

	public Users(int userid, String firstname, String lastname, Date dob,
			String email) {
		this.userid = userid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.dob = dob;
		this.email = email;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
